# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#package-ecosystem
version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    # Look for a `requirements.txt` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"